- name: Build Drupal centrally
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev"
  gather_facts: false
  tasks:
    - name: Run the build role
      include_role:
        name: drupal_build
      run_once: true