- name: Parallel dev setup
  hosts: "repo_{{ target_app | default('UNDEFINED') }}:&env_dev"
  vars_files:
    - /home/kevin/db-server/playbook/vault.yaml
    - /home/kevin/drupal/group_vars/vault.yaml
  roles:
    - role: drupal_dependencies   # Installs Apache, PHP, system tools
    - role: drupal_deploy         # Syncs files, settings.php, themes
    - role: drupal_storage        # Handles NFS/Ceph mounts
    - role: drupal_db_ops         # Runs Drush, restarts services